name: Azure Demo API CI

on:
    workflow_dispatch:
    push:
        branches:
            - --main

env:
    AZURE_WEBAPP_NAME: azure-demo-api
    AZURE_WEBAPP_PACKAGE_PATH: "/AzureDemo.Api/publish"
    DOTNET_VERSION: "9.x"
    SOLUTION_PATH: "AzureDemoApi.sln"
    API_PROJECT_PATH: "AzureDemo.Api"
    PUBLISH_DIR: "./publish"

jobs:
    build-and-test:
        name: Build and Test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: ${{ env.DOTNET_VERSION )}}

            - name: Restore
              run: dotnet restore ${{ env.SOLUTION_PATH }}

            - name: Build
              run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

            - name: Test
              run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build --verbosity normal

            - name: Publish
              run: dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore --no-build --property:PublishDir=${{ env.PUBLISH_DIR }}

            - name: Publish Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: webapp
                  path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    deploy:
        name: Deploy to Azure
        runs-on: ubuntu-latest
        needs: [build-and-test]

        steps:
            - name: Download artifacts from build job
              uses: actions/download-artifacts@v4
              with:
                  name: webapp
                  path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

            - name: Deploy
              uses: azure/webapps-depoly@v2
              with:
                  app-name: ${{ env.AZURE_WEBAPP_NAME }}
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
